package com.br.ufc.vev.Enums;

public enum Genero {
	
	AÇÃO, ANIMAÇÃO, AVENTURA, CHANCHADA, CATASTROFE, COMÉDIA, COMÉDIA_ROMANTICA, 
	COMÉDIA_DRAMATICA, COMÉDIA_DE_AÇÃO, CULT, DOCUMENTÁRIOS, DRAMA, ESPIONAGEM, 
	ERÓTICO, FANTASIA, FAROESTE, FICÇÃO_CIENTÍFICA, SÉRIES, GUERRA, MACHINIMA, 
	MUSICAL, FILME_NOIR, POLICIAL, PORNOCHANCHADA, PORNOGRÁFICO, ROMANCE, SUSPENSE, TERROR, TRASH;

}
